options(stringsAsFactors = FALSE)
required_pkgs <- c('BiocManager','edgeR','ggplot2','dplyr','tibble','ggrepel')
install_if_missing <- function(pkg){ if (!requireNamespace(pkg, quietly = TRUE)) { if (pkg=='edgeR') { if (!requireNamespace('BiocManager', quietly = TRUE)) install.packages('BiocManager', repos='https://cloud.r-project.org'); BiocManager::install(pkg, ask=FALSE, update=FALSE) } else install.packages(pkg, repos='https://cloud.r-project.org') } }
invisible(lapply(required_pkgs, install_if_missing))
library(edgeR); library(ggplot2); library(dplyr); library(tibble); library(ggrepel)
base_dir <- normalizePath('.', winslash='/', mustWork=TRUE); counts_dir <- file.path(base_dir, '7.counts'); out_dir <- file.path(base_dir, 'dropP13_report'); dir.create(out_dir, showWarnings=FALSE, recursive=TRUE)
palette_gly <- c(NC='#75ACE4', PC='#87BB8A', G25='#F9B066', G50='#E48282'); font_family <- 'sans'
extract_sample_name <- function(path) sub('_Sorted_count\\.txt$', '', basename(path)); extract_treat <- function(sample_name) { parts <- strsplit(sample_name, '-')[[1]]; if (length(parts) >= 2 && tail(parts,1)=='R') tail(parts,2)[1] else tail(parts,1) }; extract_block <- function(sample_name) paste(head(strsplit(sample_name, '-')[[1]], 2), collapse='-'); read_featurecounts <- function(path) { df <- read.delim(path, header=TRUE, sep='\t', check.names=FALSE, comment.char='#'); tibble(Geneid=df[[1]], Count=df[[ncol(df)]]) }
theme_dw <- function() { theme_minimal(base_family=font_family, base_size=12) + theme(panel.grid.minor=element_blank(), panel.grid.major=element_line(color='#EAEAEA', linewidth=0.35), axis.title=element_text(color='#111111'), axis.text=element_text(color='#111111'), axis.line=element_line(color='#444444', linewidth=0.4), axis.ticks=element_line(color='#444444', linewidth=0.35), plot.title=element_text(face='bold', size=14, color='#111111'), plot.subtitle=element_text(size=10, color='#555555'), legend.title=element_blank(), legend.position='right') }
count_files <- list.files(counts_dir, pattern='_Sorted_count\\.txt$', full.names=TRUE); count_files <- count_files[!grepl('\\.summary$', count_files)]
sample_info <- tibble(sample=vapply(count_files, extract_sample_name, character(1)), file=count_files) %>% mutate(Treat=factor(vapply(sample, extract_treat, character(1)), levels=c('NC','G25','G50','PC')), Block=vapply(sample, extract_block, character(1)))
count_list <- lapply(sample_info$file, read_featurecounts); merged <- count_list[[1]] %>% rename(!!sample_info$sample[1] := Count); for (i in 2:length(count_list)) merged <- merged %>% left_join(count_list[[i]] %>% rename(!!sample_info$sample[i] := Count), by='Geneid')
expr <- merged %>% column_to_rownames('Geneid') %>% as.matrix(); storage.mode(expr) <- 'integer'; expr <- expr[, sample_info$sample, drop=FALSE]
calc_obj <- function(info, counts) { info$Treat <- relevel(factor(info$Treat), ref='NC'); y <- DGEList(counts=counts, group=info$Treat); keep <- rowSums(cpm(y)>1)>=3; if (sum(keep)<100) keep <- rowSums(y$counts>=10)>=2; y <- y[keep,,keep.lib.sizes=FALSE]; y <- calcNormFactors(y); logcpm <- cpm(y, log=TRUE, prior.count=2); design <- model.matrix(~ Treat, data=info); colnames(design) <- make.names(colnames(design)); y2 <- estimateGLMCommonDisp(y, design); y2 <- estimateGLMTrendedDisp(y2, design); y2 <- estimateGLMTagwiseDisp(y2, design); fit <- glmFit(y2, design); sumtbl <- bind_rows(lapply(c('G25','G50','PC'), function(tr) { tt <- topTags(glmLRT(fit, coef=paste0('Treat', tr)), n=Inf, sort.by='PValue')$table; tibble(Contrast=paste0(tr,'_vs_NC'), Up=sum(tt$FDR<0.05 & tt$logFC>=1, na.rm=TRUE), Down=sum(tt$FDR<0.05 & tt$logFC<=-1, na.rm=TRUE)) %>% mutate(Total=Up+Down) })); list(y=y, logcpm=logcpm, summary=sumtbl) }
full <- calc_obj(sample_info, expr); info_drop <- sample_info[sample_info$Block != 'P1-3', , drop=FALSE]; expr_drop <- expr[, info_drop$sample, drop=FALSE]; drop <- calc_obj(info_drop, expr_drop); comp <- bind_rows(full$summary %>% mutate(Dataset='Full'), drop$summary %>% mutate(Dataset='Drop_P1-3_block')); write.csv(comp, file.path(out_dir, 'DEG_counts_full_vs_dropP13.csv'), row.names=FALSE, quote=FALSE)
make_mds <- function(y_obj, info, fn, title_text) { mds <- plotMDS(y_obj, top=1000, plot=FALSE); df <- tibble(sample=colnames(y_obj), Dim1=mds$x, Dim2=mds$y) %>% left_join(info, by='sample'); p <- ggplot(df, aes(Dim1, Dim2, color=Treat, fill=Treat)) + stat_ellipse(geom='polygon', alpha=0.14, linewidth=0.3, level=0.80, show.legend=FALSE) + geom_point(size=3.2, alpha=0.95) + ggrepel::geom_text_repel(aes(label=sample), size=3.0, family=font_family, max.overlaps=50, show.legend=FALSE) + scale_color_manual(values=palette_gly) + scale_fill_manual(values=palette_gly) + labs(title=title_text, subtitle='edgeR MDS with group polygons', x='Dimension 1', y='Dimension 2') + theme_dw(); ggsave(file.path(out_dir, paste0(fn, '.png')), p, width=7.4, height=5.8, dpi=300) }
make_pca <- function(logcpm, info, fn, title_text) { pca <- prcomp(t(logcpm), scale.=TRUE); df <- as.data.frame(pca$x[,1:2]) %>% rownames_to_column('sample') %>% left_join(info, by='sample'); colnames(df)[2:3] <- c('PC1','PC2'); p <- ggplot(df, aes(PC1, PC2, color=Treat, fill=Treat)) + stat_ellipse(geom='polygon', alpha=0.14, linewidth=0.3, level=0.80, show.legend=FALSE) + geom_point(size=3.2, alpha=0.95) + ggrepel::geom_text_repel(aes(label=sample), size=3.0, family=font_family, max.overlaps=50, show.legend=FALSE) + scale_color_manual(values=palette_gly) + scale_fill_manual(values=palette_gly) + labs(title=title_text, subtitle='Principal components with group polygons', x='PC1', y='PC2') + theme_dw(); ggsave(file.path(out_dir, paste0(fn, '.png')), p, width=7.4, height=5.8, dpi=300) }
make_mds(full$y, sample_info, 'MDS_full', 'RNA-seq MDS plot (full dataset)'); make_mds(drop$y, info_drop, 'MDS_drop_P1-3_block', 'RNA-seq MDS plot (P1-3 block removed)'); make_pca(full$logcpm, sample_info, 'PCA_full', 'RNA-seq PCA plot (full dataset)'); make_pca(drop$logcpm, info_drop, 'PCA_drop_P1-3_block', 'RNA-seq PCA plot (P1-3 block removed)'); pbar <- ggplot(comp, aes(Contrast, Total, fill=Dataset)) + geom_col(position=position_dodge(width=0.72), width=0.64) + labs(title='DEG counts before and after removing P1-3 block', subtitle='Treat-only LRT, FDR < 0.05 and |log2FC| >= 1', x=NULL, y='Number of DEGs') + theme_dw(); ggsave(file.path(out_dir, 'DEG_counts_full_vs_dropP13.png'), pbar, width=7.5, height=5.2, dpi=300); message('dropP13 report completed: ', out_dir)
