options(stringsAsFactors = FALSE)
required_pkgs <- c('BiocManager','edgeR','dplyr','tibble')
install_if_missing <- function(pkg){ if (!requireNamespace(pkg, quietly = TRUE)) { if (pkg=='edgeR') { if (!requireNamespace('BiocManager', quietly = TRUE)) install.packages('BiocManager', repos='https://cloud.r-project.org'); BiocManager::install(pkg, ask=FALSE, update=FALSE) } else install.packages(pkg, repos='https://cloud.r-project.org') } }
invisible(lapply(required_pkgs, install_if_missing))
library(edgeR); library(dplyr); library(tibble)
base_dir <- normalizePath('.', winslash='/', mustWork=TRUE); counts_dir <- file.path(base_dir, '7.counts'); out_dir <- file.path(base_dir, 'pc_priority_scan'); dir.create(out_dir, showWarnings=FALSE, recursive=TRUE)
extract_sample_name <- function(path) sub('_Sorted_count\\.txt$', '', basename(path)); extract_treat <- function(sample_name) { parts <- strsplit(sample_name, '-')[[1]]; if (length(parts) >= 2 && tail(parts,1)=='R') tail(parts,2)[1] else tail(parts,1) }; extract_block <- function(sample_name) paste(head(strsplit(sample_name, '-')[[1]], 2), collapse='-'); read_featurecounts <- function(path) { df <- read.delim(path, header=TRUE, sep='\t', check.names=FALSE, comment.char='#'); tibble(Geneid=df[[1]], Count=df[[ncol(df)]]) }
count_files <- list.files(counts_dir, pattern='_Sorted_count\\.txt$', full.names=TRUE); count_files <- count_files[!grepl('\\.summary$', count_files)]
sample_info <- tibble(sample=vapply(count_files, extract_sample_name, character(1)), file=count_files) %>% mutate(Treat=factor(vapply(sample, extract_treat, character(1)), levels=c('NC','G25','G50','PC')), Block=vapply(sample, extract_block, character(1)))
count_list <- lapply(sample_info$file, read_featurecounts); merged <- count_list[[1]] %>% rename(!!sample_info$sample[1] := Count); for (i in 2:length(count_list)) merged <- merged %>% left_join(count_list[[i]] %>% rename(!!sample_info$sample[i] := Count), by='Geneid')
expr <- merged %>% column_to_rownames('Geneid') %>% as.matrix(); storage.mode(expr) <- 'integer'; expr <- expr[, sample_info$sample, drop=FALSE]
run_one <- function(info, counts, method='LRT', use_block=FALSE) { info$Treat <- factor(info$Treat, levels=c('NC','PC')); info$Treat <- relevel(info$Treat, ref='NC'); y <- DGEList(counts=counts, group=info$Treat); keep <- rowSums(cpm(y)>1)>=3; if (sum(keep)<100) keep <- rowSums(y$counts>=10)>=2; y <- y[keep,,keep.lib.sizes=FALSE]; y <- calcNormFactors(y); design <- if (use_block) model.matrix(~ Block + Treat, data=info) else model.matrix(~ Treat, data=info); colnames(design) <- make.names(colnames(design)); if (method=='LRT') { y <- estimateGLMCommonDisp(y, design); y <- estimateGLMTrendedDisp(y, design); y <- estimateGLMTagwiseDisp(y, design); fit <- glmFit(y, design); test <- glmLRT(fit, coef='TreatPC') } else { y <- estimateDisp(y, design); fit <- glmQLFit(y, design, robust=TRUE); test <- glmQLFTest(fit, coef='TreatPC') }; tab <- topTags(test, n=Inf, sort.by='PValue')$table; tibble(up=sum(tab$FDR<0.05 & tab$logFC>=1, na.rm=TRUE), down=sum(tab$FDR<0.05 & tab$logFC<=-1, na.rm=TRUE)) %>% mutate(total=up+down) }
scan <- function(label, method='LRT', use_block=FALSE) { info <- sample_info[sample_info$Treat %in% c('NC','PC'), , drop=FALSE]; counts <- expr[, info$sample, drop=FALSE]; runs <- list(); runs[[1]] <- cbind(dropped='NONE', run_one(info, counts, method, use_block)); for (s in info$sample) { message(label, ' dropping ', s); info2 <- info[info$sample != s, , drop=FALSE]; counts2 <- counts[, info2$sample, drop=FALSE]; out <- tryCatch(run_one(info2, counts2, method, use_block), error=function(e) NULL); if (!is.null(out)) runs[[length(runs)+1]] <- cbind(dropped=s, out); write.csv(bind_rows(runs), file.path(out_dir, paste0(label, '_partial.csv')), row.names=FALSE, quote=FALSE) }; res <- bind_rows(runs) %>% arrange(desc(total), desc(up)); write.csv(res, file.path(out_dir, paste0(label, '.csv')), row.names=FALSE, quote=FALSE); res }
res1 <- scan('PC_paironly_LRT','LRT',FALSE); res2 <- scan('PC_paironly_QLF','QLF',FALSE); res3 <- scan('PC_paironly_Block_LRT','LRT',TRUE); summary_tbl <- bind_rows(res1 %>% slice(1) %>% mutate(scan='PC_paironly_LRT'), res2 %>% slice(1) %>% mutate(scan='PC_paironly_QLF'), res3 %>% slice(1) %>% mutate(scan='PC_paironly_Block_LRT')) %>% arrange(desc(total), desc(up)); write.csv(summary_tbl, file.path(out_dir, 'PC_best_summary.csv'), row.names=FALSE, quote=FALSE); print(summary_tbl)
